# Generated by Django 5.1.7 on 2025-03-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_createuserrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
