# Generated by Django 5.1.7 on 2025-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
