# Generated by Django 5.1.7 on 2025-03-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_createuserrecipe_recipe_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserRecipe',
        ),
    ]
