# Generated by Django 5.1.7 on 2025-03-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeName',
            new_name='Name',
        ),
    ]
